apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotestapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gotestapp1
  template:
    metadata:
    spec:
      containers:
      - name: gotestapp1
        image: akhilkm/gotestapp:latest
        env:
        - name: message
          value: "Hello from the environment"
        ports:
        - containerPort: 8000